name = "mapped"
version = "1.0.0"

description = "An implementation of a Bidirectional Map in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "GearsDatapacks", repo = "gleam-mapped" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
